kind: Pod
apiVersion: V1
metadata: 
  name: annotations
  annotataions:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
   