kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment:  dev
    version: "1.0.0"
  ports:
  - protocol: TCP
    ports: 80
    targetport: 80


---
kind: Pod
apiVersion: v1
metadata: 
  name: backend
  labels:
      project: expense
      module: backend
      environment:  dev
      version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
   