kind: Service
apiVersion: v1
metadata:
  name: nginx-1b
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment:  dev
    version: "1.0.0"
    demo: 1b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 30007


---
kind: Pod
apiVersion: v1
metadata: 
  name: backend-1b
  labels:
    project: expense
    component: backend
    environment:  dev
    version: "1.0.0"
    demo: 1b
spec:
  containers:
  - name: nginx
    image: nginx
   