apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: frontend
    tier: web
spec:
  replicas: 3
  selelctor:
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx